### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ErAshu** [princesojitra/ExpandableTableView#1]
You have tested with 3 section. 
Please test with more section which can scroll. Then expand very first section and then scroll to last section and try to expand. App will crash.

I got the issue, there is a variable cImageView which gets nil if cell is not visible.

Please correct this.

**Comment by princesojitra** [comment]
I didn't get any crash. Check for the same: https://www.dropbox.com/s/kpcnbnr4v48o76j/Screen%20Recording%202020-06-20%20at%201.04.08%20PM.mov?dl=0

**Comment by princesojitra** [comment]
> You have tested with 3 section.
> Please test with more section which can scroll. Then expand very first section and then scroll to last section and try to expand. App will crash.
> 
> I got the issue, there is a variable cImageView which gets nil if cell is not visible.
> 
> Please correct this.

I didn't get any crash. Check for the same: https://www.dropbox.com/s/kpcnbnr4v48o76j/Screen%20Recording%202020-06-20%20at%201.04.08%20PM.mov?dl=0
